### PR TITLE
BMBT Brightness Control & Request

### PR DESCRIPTION
**Pull request by multilan-tarek**
Hi!
Here are the messages for controlling and requesting the brightness of the BMBT.
Captured from an MK4.

I couldn't figure out how BMW came up with these brightness steps. Theoretically you can also send your own values.

### CODE REVIEW

**Comment by piersholt** [comment]
G'day @multilan-tarek!

I'm sorry I didn't comment sooner. Real life can get in the way sometimes!

I do have some further info on this command, but I wanted to merge it into the repository now so you weren't left waiting.

**Comment by piersholt** [comment]
Okay, so I had a few [notes](https://github.com/piersholt/walter/blob/develop/lib/wilhelm/virtual/protocol/map/commands.yaml#L114) about this command, but I wasn't motivated to investigate further until your pull request.

It did always strike me as odd that brightness was configured using `0x05` and `0x06`. While commands don't have a global scope (i.e. a command ID can mean different things to different modules), it seemed cavalier to repurpose a diagnostic command ID (i.e. `0x00` through `0x0f`) as, to the best of my knowledge, they're the few command IDs that _are_ global (i.e. `0x00` is an ident request regardless of which module sends it, or whether it's on the D, K, or I-Bus).

So, it turns out there's a little more to `0x05` and `0x06`, and it looks like it relates to service mode!

(I find this really quite exciting, which is why I call people like myself and @tedsalmon 'BMW losers'.)

To the logs!

_standby..._

**Comment by piersholt** [comment]
Good thing I've been capturing all bus traffic since 2018! It looks like I was poking around this functionality in 2020. Below is a snippet of traffic whereby I was generating `0x05` commands from the GT.

It looks like the first byte is maybe a property ID, and the second byte is perhaps a function ID (i.e. read/write).

I'm guessing this is to populate the service mode displays related to the BMBT. I reckon if you open service mode you'll see similar traffic, albeit with different return values?

```
3B 05 F0 05 00 01 CA
F0 13 3B 06 86 91 33 87 43 00 31 10 22 01 17 42 00 00 00 00 69 # looks like module ident

3B 05 F0 05 04 01 CE
F0 0C 3B 06 04 01 1F 16 0A 03 1F 0B 1F CF
F0 04 3B 06 00 C9

3B 05 F0 05 0B 01 C1
F0 06 3B 06 FF 00 00 34

3B 05 F0 05 1C 01 D6
F0 04 3B 06 00 C9

3B 05 F0 05 40 01 8A
F0 04 3B 06 8B 42


# giving 02 a go... but less success

3B 05 F0 05 00 02 C9
F0 13 3B 06 86 91 33 87 43 00 31 10 22 01 17 42 00 00 00 00 69 # same ident
```

**Comment by multilan-tarek** [comment]
Very interesting!
The brightness control in the service menu seems to have more or less the same function as the one in the settings menu, except that it only sends the command '0x41'. Also with the VID, only '0x41' is sent in the service menu. The option in the settings seems to have only been available later, as it does not yet exist on the MK3. Maybe '0x42' is needed for the later flip-up displays like in the E83?

I also tested all the commands again with my BMBTs. For some reason there was no answer for '3B 05 F0 05 1C 01 D6'.

```
BMBT 1 (Prod. 11/01, AI: 02, INDEX 03):

3B 05 F0 05 00 01 CA  # Ident
F0 13 3B 06 86 91 33 87 43 00 31 10 17 01 17 42 00 00 00 00 5C

3B 05 F0 05 04 01 CE
F0 0C 3B 06 04 16 3F 01 1F 03 3F 0B 1F DA
F0 04 3B 06 00 C9

3B 05 F0 05 0B 01 C1  # Button test
F0 06 3B 06 FF 00 00 34

3B 05 F0 05 1C 01 D6
<-NO RESPONSE->

3B 05 F0 05 40 01 8A  # Brightness request
F0 04 3B 06 48 81

BMBT 2 (Prod. 50/02, AI: 01, INDEX: 15):

3B 05 F0 05 00 01 CA  # Ident
F0 13 3B 06 86 93 44 12 54 00 31 10 50 02 17 49 00 00 00 00 E4

3B 05 F0 05 04 01 CE
F0 0A 3B 06 03 03 3F 01 1F 16 02 F2
F0 04 3B 06 00 C9

3B 05 F0 05 0B 01 C1  # Button test
F0 06 3B 06 FF 00 00 34

3B 05 F0 05 1C 01 D6
<-NO RESPONSE->

3B 05 F0 05 40 01 8A  # Brightness request
F0 04 3B 06 3C F5
```

**Comment by piersholt** [comment]
> Very interesting!

IKR! 😝

> The option in the settings seems to have only been available later, as it does not yet exist on the MK3.

Curious. I did note it wasn't available in the legacy UI, but I assumed it was always available in the new UI. Do you know what software version the MK-3 was running? The new UI was introduced at `3-1/40`.

_Maybe_ it's related to the nav's hardware architecture? I believe MK3 was still 68k, but I know my MK4 is MIPS, so entirely different software builds.

> The brightness control in the service menu seems to have more or less the same function as the one in the settings menu, except that it only sends the command '0x41'. Also with the VID, only '0x41' is sent in the service menu. Maybe '0x42' is needed for the later flip-up displays like in the E83?

I did notice this, and I had a similar thought about `0x42`, albeit I was thinking about the Rear Compartment Monitor (RCM). I don't have access to either an RCM or flip up display in order to test, but we're on the same page.


I've now mapped out the service mode functionality, and I just need to add it to your branch, then I'll merge into master.

I found a couple of other service mode things- telematics off the top of my head. It's a curious command.. it might warrant some further poking and prodding! 😄

**Comment by multilan-tarek** [comment]
> Curious. I did note it wasn't available in the legacy UI, but I assumed it was always available in the new UI. Do you know what software version the MK-3 was running? The new UI was introduced at 3-1/40.

I do not own a MK3 myself, but there are a few videos on YouTube where you can see that the option for brightness is missing:
- https://youtu.be/YGM07DZoKoo?t=246
- https://youtu.be/wZ_Frl3msZE?t=753
- https://youtu.be/KB4CaKQ1CWA?t=403

> Maybe it's related to the nav's hardware architecture? I believe MK3 was still 68k, but I know my MK4 is MIPS, so entirely different software builds.

The MK3 already had the "MIPS OS 9" Sticker. I also found some MIPS copyright stuff in the loader.ini file on the software disc. See https://www.ebay.ca/itm/384358905929

> I did notice this, and I had a similar thought about 0x42, albeit I was thinking about the Rear Compartment Monitor (RCM). I don't have access to either an RCM or flip up display in order to test, but we're on the same page.

Wasn't the RCM only available on the E38? At least to my knowledge, the MK4 was never officially available on the E38.
Even if it's used for the flip-up displays, it would be kind of odd that they would use a different command.
Also, the option in the service menu would then possibly be useless.

I actually found two RCMs on the biggest german 'craigslist-like' website, but they are a little bit too expensive :D
https://www.kleinanzeigen.de/s-anzeige/bmw-e38-fondmonitor-individual-fondbildschrim-s603a/2649760605-223-9433
https://www.kleinanzeigen.de/s-anzeige/bmw-e38-fondmonitor-individual-fondbildschirm-s603a/2649758003-223-9433

**Comment by piersholt** [comment]
Sorry, I finally caught the big C, family dramas etc etc. Just catching up now!

**Comment by piersholt** [comment]
@multilan-tarek would you like to check the docs before I merge them in?

I rushed a little because this has been open so long!

https://github.com/piersholt/wilhelm-docs/blob/feature/0x05_0x06/gt/05.md

https://github.com/piersholt/wilhelm-docs/blob/feature/0x05_0x06/bmbt/06.md

**Comment by piersholt** [comment]
In response to your comments @multilan-tarek:

> I do not own a MK3 myself, but there are a few videos on YouTube where you can see that the option for brightness is missing:

Interesting...! The MK3 in the last video was running `3/1-63`, which was the final build for MK3.. so perhaps it was only available on MK4!

(I'm glad I'm not the only one who trawls through YouTube to get examples of UI! I can't tell you how many radio functions I've worked out by doing this..! Australia has very limited RDS, and I'm not aware of any vehicles equipped with dual tuner radios.)

> The MK3 already had the "MIPS OS 9" Sticker. I also found some MIPS copyright stuff in the loader.ini file on the software disc.

Interesting, I didn't know MK3 was MIPS! I admit, I've never looked at the MK3 builds on the software disc as I've always been 4-1/00 focused, so I never picked up any hints on the architecture.

> Wasn't the RCM only available on the E38? At least to my knowledge, the MK4 was never officially available on the E38.
Even if it's used for the flip-up displays, it would be kind of odd that they would use a different command.
Also, the option in the service menu would then possibly be useless.

I believe RCM was only available in the E38. However, even if the MK4 was not factory fitted in E38, I'd not expect the MK4 builds to exclude the E38 functionality...? 

Partly, just due to backwards compatibility, but also.. as @tedsalmon and I have found, BMW didn't hesitate to cut corners, and add hack after hack to support new functionality (particularly towards of the OS-9 platform lifecycle)! For example, the early BM radios are MID radios with some sprinkles. The software of the C23 BM fitted to my 1997 E39 is so sloppy, it actually attempts to draw to a MID, and responds to MID button presses!

The RCM functionality isn't much better... It's essentially two GTs running in parallel (NAV GT  and VM GT) with the VM GT having the ability to override the NAV GT in order to switch to Navigation, which the VM GT then switches to as an external video feed. It's absolutely hack-tastic! (Incidentally, Ivan- who contributes to BlueBus, has implemented a number of features using an [RCM related command](https://github.com/piersholt/wilhelm-docs/blob/feature/ses/ses/aa.md)!)

Grasping at straws, but... maybe `0x41` and `0x42` are... memory write locations/offsets or something? Given it's MK4- so late in lifecycle, and `0x05` and `0x06` are in what I considered to be reserved scope for diagnostic commands... maybe it really is that nasty?

> I actually found two RCMs on the biggest german 'craigslist-like' website, but they are a little bit too expensive :D

Holy moly! No thanks! I think I'll just buy an E38 equipped with one! It probably wouldn't be much more expensive!

**Comment by piersholt** [comment]
Okay, I just merged it in anyway. No reason it can't be tweaked later! 😄

**Comment by multilan-tarek** [comment]
Hi! Sorry for the late answer.

> https://github.com/piersholt/wilhelm-docs/blob/feature/0x05_0x06/gt/05.md
> 
> https://github.com/piersholt/wilhelm-docs/blob/feature/0x05_0x06/bmbt/06.md

Looks good!

> Interesting...! The MK3 in the last video was running 3/1-63, which was the final build for MK3.. so perhaps it was only available on MK4!

Maybe some owners complained about the missing Night Mode on the MK3 New UI and BMW/Siemens VDO quickly added this to the MK4 Software so people can lower the brightness at night even more than with the hardware brightness dial.
But who knows...

> (I'm glad I'm not the only one who trawls through YouTube to get examples of UI! I can't tell you how many radio functions I've worked out by doing this..! Australia has very limited RDS, and I'm not aware of any vehicles equipped with dual tuner radios.)

Yeah, I do this quite often too. :D

> I believe RCM was only available in the E38. However, even if the MK4 was not factory fitted in E38, I'd not expect the MK4 builds to exclude the E38 functionality...?

You're probably right. I don't think they removed legacy functions. Would be more work than necessary for them. :P

> Partly, just due to backwards compatibility, but also.. as @tedsalmon and I have found, BMW didn't hesitate to cut corners, and add hack after hack to support new functionality (particularly towards of the OS-9 platform lifecycle)! For example, the early BM radios are MID radios with some sprinkles. The software of the C23 BM fitted to my 1997 E39 is so sloppy, it actually attempts to draw to a MID, and responds to MID button presses!

> The RCM functionality isn't much better... It's essentially two GTs running in parallel (NAV GT and VM GT) with the VM GT having the ability to override the NAV GT in order to switch to Navigation, which the VM GT then switches to as an external video feed. It's absolutely hack-tastic! (Incidentally, Ivan- who contributes to BlueBus, has implemented a number of features using an [RCM related command](https://github.com/piersholt/wilhelm-docs/blob/feature/ses/ses/aa.md)!)

That sounds like hell and i like it!

There is probably much more hackery like this out there, which didn't get to see the light of day. 
Just look at this RCM like thing in this BMW Service Video about Fibre Optics in the E65:
https://youtu.be/aNAmBDGX4uY?t=72
I never seen this thing anywhere else, but it's quite cool i think.

**Comment by multilan-tarek** [comment]
> Australia has very limited RDS, and I'm not aware of any vehicles equipped with dual tuner radios.)

I actually have some data for the "NG Station List" command.
And maybe some other stuff.

I have an ongoing project, for nearly 1,5 years now, where I rebuild the MK4 UI in PyQT.
It's meant to replace my MK4 when the project is finished.
Im currently designing a prototype board with a Compute Module 4, GPS and some other stuff.
The video will be outputed directly as RGB Signals that the Monitor and/or Video Module can understand.
So no noisy composite video car pc thing.

2FE84D9C-A2CF-443D-BA55-D717CEE38ED8

https://github.com/piersholt/wilhelm-docs/assets/34243288/041b4c5f-bc71-4129-89b3-d68170a74840

**Comment by piersholt** [comment]
> Maybe some owners complained about the missing Night Mode on the MK3 New UI and BMW/Siemens VDO quickly added this to the MK4 Software so people can lower the brightness at night even more than with the hardware brightness dial.
But who knows...

I can 100% see a room full of German engineers being annoyed that customers want to override their perfectly engineered 58G automatic brightness adjustment. 

To be fair, I do understand that frustration.. I recall someone requesting BlueBus add support for automatic adjustment of the brightness level in addition to the automatic adjustment via 58G, and my neurodivergent/German brain couldn't wrap my head around it..  _"but ze software already does zis!"_ 

Ted and I spent an eternity working on the BlueBus lighting features, which ostensibly had to be written eight times owing to the number of light module variants... the cluster's independent backlighting brightness adjustment was.. painful...  (I'd show you the source.. but BMW AG issued a DMCA takedown notice on that one...)

> That sounds like hell and i like it!

Ted has the best BMW hackery examples. You could tell by the late E46 module software, that the engineers had just given up 😂

> There is probably much more hackery like this out there, which didn't get to see the light of day. Just look at this RCM like thing in this BMW Service Video about Fibre Optics in the E65:
https://youtu.be/aNAmBDGX4uY?t=72
I never seen this thing anywhere else, but it's quite cool i think.

OH. MY. GOD! It _looks_ like an RCM (volume dial, nav dial, menu button, headphone jack)... but there's *two* of them.. and an LCD panel affixed to the centre console?!

> I actually have some data for the "NG Station List" command. And maybe some other stuff.

That would be very interesting. I've aggregated bus logs from BlueDev development and debugging and picked up a few RDS details, but reverse engineering commands from logs is a blackbox exercise at best.

> I have an ongoing project, for nearly 1,5 years now, where I rebuild the MK4 UI in PyQT.
It's meant to replace my MK4 when the project is finished.
Im currently designing a prototype board with a Compute Module 4, GPS and some other stuff.
The video will be outputed directly as RGB Signals that the Monitor and/or Video Module can understand.
So no noisy composite video car pc thing.

Wait, what?! I was trying to figure out why I didn't recognise the date and time adjustment, then I watched the video... that's your PyQT interface?!

**Comment by multilan-tarek** [comment]
> I can 100% see a room full of German engineers being annoyed that customers want to override their perfectly engineered 58G automatic brightness adjustment.

Yeah I can see that too. xD

> OH. MY. GOD! It looks like an RCM (volume dial, nav dial, menu button, headphone jack)... but there's two of them.. and an LCD panel affixed to the centre console?!

How does that navigation view actually work? Will that force the front screen to also display the map?
This is probably a complete mess in combination with the new ui...? XD

> That would be very interesting. I've aggregated bus logs from BlueDev development and debugging and picked up a few RDS details, but reverse engineering commands from logs is a blackbox exercise at best.

I can definitely provide some testing data!

> Wait, what?! I was trying to figure out why I didn't recognise the date and time adjustment, then I watched the video... that's your PyQT interface?!

Yep!
The whole thing is of course fairly modular with widgets and plugins.
I want to do stuff like PDC view, temperature views, maybe some way to control the system using the MFL and have the currently selected elements text displayed in the IKE and much more.
The navigation plugin will be build using OpenStreetMaps, Brouter for offline routing and a little offline reverse geocoding database I wrote. I already can display a map, that looks almost like the original MK4 map. This is done using pregenerated svg tiles.

**Comment by piersholt** [comment]
> How does that navigation view actually work? Will that force the front screen to also display the map? This is probably a complete mess in combination with the new ui...? XD

Exactly correct!

As far as I can make out, the RCM variant of the video module (A197) is essentially a MK1 video module\*, but with an additional 26-pin connector (X18803) which outputs RGB video to the RCM. However, unlike the standard video module which won't activate it's GT if a functioning navigation computer is present, the GT of the RCM video module will run in parallel- albeit, output to the RCM.

Given there is only a single navigation video source, when you select 'Navigation' from the RCM, the command `0xaa` is sent to the navigation computer GT to switch to Navigation, at which point the RCM GT will output the navigation video signal which is being passed through the VM.

It's... **_nasty_**!

\* After looking at some of the pictures I've compiled of the RCM system over the years... it looks like the RCM variant of the video module can still function as an independent fallback GT (in cars with TV but no nav, or non-functioning navigation computer). As such, it's possible that the RCM video module actually has a second 68k system rather than just leveraging an otherwise dormant legacy 68k GT- or maybe it's not 68k at all?!

> Yep!
The whole thing is of course fairly modular with widgets and plugins.
I want to do stuff like PDC view, temperature views, maybe some way to control the system using the MFL and have the currently selected elements text displayed in the IKE and much more.
The navigation plugin will be build using OpenStreetMaps, Brouter for offline routing and a little offline reverse geocoding database I wrote. I already can display a map, that looks almost like the original MK4 map. This is done using pregenerated svg tiles.

Holy moly! That's awesome! That really pushes my 'OEM' buttons! I have many more questions!

I had a similar widget/plugin architecture concept, but it was leveraging the navigation GT. Without the factory radio or telephone, it was reasonably effective, but I was left wanting when it came to more advanced displays. I went as far as calculating the relative weight of the variable width font on the [MP3 ID3 display](https://github.com/piersholt/walter/tree/develop/lib/wilhelm/sdk#user-interface) in some desperate attempt to ASCII art my way to custom displays...  It _was not_ a success 🤣 

Ted and I joked about re-writing the OS-9 software for the later MIPS systems, but we realised it was an _absolutely terrible_ idea... 

However, a handful of the BlueBlus nerds are working on a Apple CarPlay/Android Auto solution.

Shall I invite you to the BlueBus Slack? It's just other seriously tragic BMW nerds who also look for obscure YouTube videos for examples of legacy UIs! You'd be among friends.. 😛

**Comment by piersholt** [comment]
This is a compilation of photos from an auction listing for an E38 with RCM. I just noted there's no navigation, but still two independent GTs running from the RCM video module, hence why I think possibly two discrete 68k (or similar) systems.

The GT displayed on the BMBT looks like the later MK3-era GT that we jokingly refer to as 'Super Mario Bros. 8-bit'. Whereas the GT displayed on the RCM looks like the MK1 era GT.

I'm unsure if you've opened up an MK1 video module, but it's literally a TV tuner, with a discrete 68k system sandwiched on top of it. This 68k system was integrated into the MK2 navigation computer, at which point the video module was a huge, mostly empty metal box with a tiny TV tuner in it.

front and rear b5372e99fc250b2ed448b5f47c3569c8_288188 copy

**Comment by multilan-tarek** [comment]
> As far as I can make out, the RCM variant of the video module (A197) is essentially a MK1 video module*, but with an additional 26-pin connector (X18803) which outputs RGB video to the RCM. However, unlike the standard video module which won't activate it's GT if a functioning navigation computer is present, the GT of the RCM video module will run in parallel- albeit, output to the RCM.

> Given there is only a single navigation video source, when you select 'Navigation' from the RCM, the command 0xaa is sent to the navigation computer GT to switch to Navigation, at which point the RCM GT will output the navigation video signal which is being passed through the VM.

> It's... nasty!

> * After looking at some of the pictures I've compiled of the RCM system over the years... it looks like the RCM variant of the video module can still function as an independent fallback GT (in cars with TV but no nav, or non-functioning navigation computer). As such, it's possible that the RCM video module actually has a second 68k system rather than just leveraging an otherwise dormant legacy 68k GT- or maybe it's not 68k at all?!

I guess they probably knew that not many people would have bought this, so they didn't even really bothered. 🤣 
Probably the same as with the ACC.
Mercedes brought it first to the market, so BMW had to hack something together in no time.
The E38 ACC LED Cluster is so quirky.

> Holy moly! That's awesome! That really pushes my 'OEM' buttons! I have many more questions!

Feel free to ask! 😁 Maybe you are also interested in contributing?

> I had a similar widget/plugin architecture concept, but it was leveraging the navigation GT. Without the factory radio or telephone, it was reasonably effective, but I was left wanting when it came to more advanced displays. I went as far as calculating the relative weight of the variable width font on the [MP3 ID3 display](https://github.com/piersholt/walter/tree/develop/lib/wilhelm/sdk#user-interface) in some desperate attempt to ASCII art my way to custom displays... It was not a success 🤣

Still, its incredible what you can do with the MK4 GT and the whole bus architecture of the E-series cars.
Replacing the graphics stage completely always feels a bit like cheating, because its kind of the easy way out.
But you can do so much more with a clean base.

> Ted and I joked about re-writing the OS-9 software for the later MIPS systems, but we realised it was an absolutely terrible idea...

Yeah... I once was at that point too.
I used Ghidra and https://github.com/kevinhartman/mwos-ghidra to decompile the individual modules from the MK4 Software.
Actually, i got some readable code out of it. Although I pretty quickly realized, that this was going to be an impossible project. 🤣

> However, a handful of the BlueBlus nerds are working on a Apple CarPlay/Android Auto solution.

I read about this in an BlueBus GitHub Issue. Is it this one? https://github.com/AidFTech/MKA-Lite
Thought about integrating something like this in my own module, but I didn't wanted to go that route in the end, because it would add multiple layers of complexity to my project.

But I want to add Spotify and Apple Music Support in the end, so that users can browse through they're playlists. 
Actually, I already added something like this using the AVRCP Bluetooth Profile, but this was sooo slow.

> Shall I invite you to the BlueBus Slack? It's just other seriously tragic BMW nerds who also look for obscure YouTube videos for examples of legacy UIs! You'd be among friends.. 😛

Oh yeah, that would be awesome!

**Pull request merged**
