### PR TITLE
New Odometer, Speed/RPM info - readme update to target the new files

### PR DESCRIPTION
**Pull request by Padamdam**

### CODE REVIEW

**Comment by piersholt** [comment]
Hi @Padamdam, I'll take a look at this after Christmas 😄

**Comment by piersholt** [comment]
I've not forgotten this @Padamdam!

I'm working on finishing an overdue feature on [BlueBus](https://github.com/tedsalmon/BlueBus) after which I'll have some spare brainpower 😄

**Comment by Padamdam** [comment]
No worries @piersholt ! I keep working on it and will soon have some other documentation to add.

Good luck on BlueBus :)

**Comment by piersholt** [comment]
Hi @Padamdam, thanks for hanging in there.

I must admit, I didn't expect any contributions to this project so I didn't think to write any contribution guidelines.

It's a little late in this case- which is my fault, but I've done a quick [guide](https://github.com/piersholt/wilhelm-docs/blob/master/CONTRIBUTING.md), and [template](https://github.com/piersholt/wilhelm-docs/blob/master/guide.md).

Would you be kind enough to open pull requests for each individual command you've documented? I appreciate there's some leg work in doing so, but it will make reviewing the commands a little easier.

For reference, I use a branch for each command. It allows me to jump between them, and makes releases easier to manage.

branches

**Comment by Padamdam** [comment]
Hey,

Sorry for the delay, i've created three separate PR for the three features covered here.

**Comment by piersholt** [comment]
Hey @Padamdam - thanks for that! I'm getting myself back up to speed now. I'll review the PRs in the next few weeks ❤️

**Pull request closed without merging**
